twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    globals:
        date_calculator: '@App\Service\Helper\DateCalculator'
        status_generator: '@App\Service\Helper\StatusGenerator'