vich_uploader:
    db_driver: orm

    mappings:
        users_pictures:
            uri_prefix: /images/users_pictures
            upload_destination: '%kernel.project_dir%/public/images/users_pictures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        articles_pictures:
            uri_prefix: /images/articles_pictures
            upload_destination: '%kernel.project_dir%/public/images/articles_pictures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true           