<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAoFDsFW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAoFDsFW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAoFDsFW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAoFDsFW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAoFDsFW\App_KernelDevDebugContainer([
    'container.build_hash' => 'AoFDsFW',
    'container.build_id' => '76f2223d',
    'container.build_time' => 1585563622,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAoFDsFW');
